### ISSUE TITLE
Error occurs when running "python3 run.py" 

### ISSUE THREAD

**Issue by fucker-cracker** [PearLoveTana/Celeritas#2]
After running "pip3 install.", I got errors below when running "python3 run.py"

```
Traceback (most recent call last):
  File "run.py", line 5, in <module>
    from instance.run_obgn_arxiv import run_ogbn_arxiv
  File "/workspace/Celeritas/python_script/instance/run_obgn_arxiv.py", line 1, in <module>
    from celeritas.utils.preprocessing.dataset.ogbn_arxiv import OGBNArxiv
  File "/opt/conda/lib/python3.8/site-packages/celeritas/utils/preprocessing/dataset/ogbn_arxiv.py", line 5, in <module>
    from celeritas.utils.preprocessing.converter.to_tensor import TorchEdgeListConverter
  File "/opt/conda/lib/python3.8/site-packages/celeritas/utils/preprocessing/converter/to_tensor.py", line 5, in <module>
    import torch
  File "/opt/conda/lib/python3.8/site-packages/torch/__init__.py", line 196, in <module>
    from torch._C import *
RuntimeError: generic_type: type "Module" is already registered!
```

I'm running it in a docker env(torch version==1.80 && cuda version = 11.1)

**Comment by rain0831** [comment]
@fucker-cracker  I am facing the same issue; how have you resolved this?
